# Generated by c.py
# Atul Varma (Spring 2004)

    .text
    .global main
main:
  pushl %ebp
  movl %esp, %ebp
  movl $-1, %eax
  jmp .L0_function_end
.L0_function_end:
  movl %ebp, %esp
  popl %ebp
  ret

.global_vars:

